import React from "react";
import {
  Footprints,
  Mountain,
  MountainSnow,
  Pickaxe,
  Grip,
  Bike,
  Motorbike,
  Car,
  Sun,
  Flashlight,
  TrendingDown,
  Building2,
  Wind,
  Sunrise,
  Anchor,
  Sailboat,
  Waves,
  Ship,
  Fish,
  Snowflake,
  CloudSnow,
  Zap,
  PlaneLanding,
  Triangle,
} from "lucide-react";

export const ADVENTURE_TYPE_ICONS: Record<string, (size?: number) => React.ReactNode> = {
  Trekking:          (s = 14) => <Footprints    style={{ width: s, height: s }} />,
  Mountaineering:    (s = 14) => <MountainSnow  style={{ width: s, height: s }} />,
  "Rock Climbing":   (s = 14) => <Pickaxe       style={{ width: s, height: s }} />,
  Scrambling:        (s = 14) => <Grip          style={{ width: s, height: s }} />,
  Biking:            (s = 14) => <Motorbike     style={{ width: s, height: s }} />,
  Cycling:           (s = 14) => <Bike          style={{ width: s, height: s }} />,
  "Jeep Safari":     (s = 14) => <Car           style={{ width: s, height: s }} />,
  Caving:            (s = 14) => <Flashlight    style={{ width: s, height: s }} />,
  Sandboarding:      (s = 14) => <TrendingDown  style={{ width: s, height: s }} />,
  "Urban Adventure": (s = 14) => <Building2     style={{ width: s, height: s }} />,
  Paragliding:       (s = 14) => <Wind          style={{ width: s, height: s }} />,
  "Hot Air Balloon": (s = 14) => <Sunrise       style={{ width: s, height: s }} />,
  Diving:            (s = 14) => <Anchor        style={{ width: s, height: s }} />,
  Kayaking:          (s = 14) => <Sailboat      style={{ width: s, height: s }} />,
  Surfing:           (s = 14) => <Waves         style={{ width: s, height: s }} />,
  "River Rafting":   (s = 14) => <Ship          style={{ width: s, height: s }} />,
  Snorkelling:       (s = 14) => <Fish          style={{ width: s, height: s }} />,
  Skiing:            (s = 14) => <Snowflake     style={{ width: s, height: s }} />,
  Snowboarding:      (s = 14) => <CloudSnow     style={{ width: s, height: s }} />,
  "Ice Climbing":    (s = 14) => <Zap           style={{ width: s, height: s }} />,
  "Snow Trekking":   (s = 14) => <MountainSnow  style={{ width: s, height: s }} />,
  Skydiving:         (s = 14) => <PlaneLanding  style={{ width: s, height: s }} />,
  "Hang Gliding":    (s = 14) => <Triangle      style={{ width: s, height: s }} />,
};
